# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20161017_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
